import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Additional ignores on top of eslint-config-next's own defaults (the
  // imported Next configs still carry their own ignore entries; this array
  // is additive, not a replacement for them).
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Nested agent worktrees may contain their own generated Next build output.
    ".claude/worktrees/**",
    // Generated by `npx supabase start` (gitignored, but not linted):
    "supabase/.temp/**",
  ]),
  {
    // Keep the repository's established TypeScript/React patterns lintable
    // while the application is migrated incrementally to the newest Next
    // compiler diagnostics. Typecheck remains the type-safety gate.
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-this-alias": "off",
      "react-hooks/immutability": "off",
      "react-hooks/static-components": "off",
      "@next/next/no-assign-module-variable": "off",
      "prefer-const": "off",
    },
  },
]);

export default eslintConfig;
