import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Additional ignores on top of eslint-config-next's own defaults (the
  // imported Next configs still carry their own ignore entries; this array
  // is additive, not a replacement for them).
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npx supabase start` (gitignored, but not linted):
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
