#!/usr/bin/env node
/** Read-only audit of billing-date coverage for the fiscal RBT12 window. */
import 'dotenv/config'
import { createAdminSupabaseClient } from '@/lib/supabase/admin'
import { fetchAllPages } from '@/lib/reconciliation/run'
const orgId = process.argv[2] ?? process.env.WEE_ORG_ID
type Order = { id: string; data: string | null; data_faturamento: string | null; id_nota_fiscal: number | null; valor_total_pedido: number | null; situacao: string | number | null; raw: Record<string, unknown> | null }
const norm = (value: unknown) => String(value ?? '').trim().toLowerCase()
const money = (value: number) => Math.round(value * 100) / 100
const dateOnly = (value: string | null | undefined) => value?.slice(0, 10) ?? null
const isCancelled = (row: Order) => [row.situacao, row.raw?.situacao, row.raw?.situacaoNome, row.raw?.situacao_nome].some((value) => ['cancelado', 'cancelada', 'cancelled', 'canceled', 4, 9].includes(value as never) || ['cancelado', 'cancelada', 'cancelled', 'canceled'].includes(norm(value)))
function classify(row: Order) { if (isCancelled(row)) return 'CANCELLED'; if (row.data_faturamento) return 'INVOICED'; if (row.id_nota_fiscal) return 'SOURCE_MISSING_FIELD'; const status = norm(row.raw?.situacaoNome ?? row.raw?.situacao_nome ?? row.situacao); if (['aberto', 'aprovado', 'preparando_envio', 'pronto_envio', 'pre_invoice', 'pre-invoice'].includes(status) || [0, 1, 2].includes(Number(row.situacao))) return 'PRE_INVOICE'; if (row.raw && ('dataFaturamento' in row.raw || 'idNotaFiscal' in row.raw)) return 'NOT_INVOICED'; return 'OTHER' }
async function main() { if (!orgId) throw new Error('Informe o org_id como primeiro argumento ou WEE_ORG_ID'); const admin = createAdminSupabaseClient(); const orders = await fetchAllPages<Order>((from, to) => admin.from('olist_orders').select('id,data,data_faturamento,id_nota_fiscal,valor_total_pedido,situacao,raw').eq('org_id', orgId).range(from, to), 'Falha ao carregar olist_orders'); const start = '2025-09-01'; const end = '2026-09-01'; const inWindow = orders.filter((row) => { const sourceDate = dateOnly(row.data_faturamento || row.data); return Boolean(sourceDate && sourceDate >= start && sourceDate < end && Number(row.valor_total_pedido ?? 0) > 0 && !isCancelled(row)) }); const windowWithInvoice = inWindow.filter((row) => Boolean(row.data_faturamento)); const missingByClass = Object.fromEntries(['NOT_INVOICED', 'CANCELLED', 'SOURCE_MISSING_FIELD', 'PRE_INVOICE', 'OTHER'].map((key) => [key, orders.filter((row) => { const orderDate = dateOnly(row.data); return Boolean(orderDate && orderDate >= start && orderDate < end && !row.data_faturamento && classify(row) === key) }).length])); const allMissing = orders.filter((row) => !row.data_faturamento && Number(row.valor_total_pedido ?? 0) > 0); console.log(JSON.stringify({ RBT12_PERIOD: '2025-09..2026-09 (exclusive)', RBT12_WINDOW_ORDERS: inWindow.length, RBT12_WINDOW_WITH_INVOICE_DATE: windowWithInvoice.length, RBT12_WINDOW_WITHOUT_INVOICE_DATE: inWindow.length - windowWithInvoice.length, RBT12_COVERAGE_PERCENT: inWindow.length ? money(windowWithInvoice.length / inWindow.length * 100) : 0, MISSING_DATA_FATURAMENTO_TOTAL: allMissing.length, MISSING_CLASSIFICATION_BY_ORDER_DATE_WINDOW: missingByClass, RBT12_GROSS_REVENUE: money(windowWithInvoice.reduce((sum, row) => sum + Number(row.valor_total_pedido ?? 0), 0)), RULE: 'RBT12 usa somente data_faturamento; data do pedido não é fallback fiscal.', CLASSIFICATION_RULES: { NOT_INVOICED: 'sem nota fiscal e sem data de faturamento', CANCELLED: 'situação cancelada', SOURCE_MISSING_FIELD: 'id_nota_fiscal presente, mas data_faturamento ausente', PRE_INVOICE: 'pedido ainda aberto/aprovado/sem faturamento', OTHER: 'não enquadrado nas regras anteriores' } }, null, 2)) }
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1 })
